services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            $csrfTokenManager: '@contao.csrf.token_manager'
            $csrfTokenName: '%contao.csrf_token_name%'
    
    InspiredMinds\ContaoIsotopeEditOrderAddresses\EventListener\DataContainer\ProductCollectionAddressesCallback:
        public: true
